const punjabiKeywords = [
  "নতুন ডিজাইনের পাঞ্জাবি",
  "ঈদের পাঞ্জাবি",
  "পাঞ্জাবি",
  "কম দামে পাঞ্জাবি",
  "পাইকারি দামে পাঞ্জাবি",
  "পাঞ্জাবি ডিজাইন",
  "পাঞ্জাবি পাইকারি মার্কেট ঢাকা",
  "পাঞ্জাবি পাইকারি বাজার",
  "পাঞ্জাবি পাইকারি মার্কেট",
  "পাঞ্জাবি কিনুন",
  "পাঞ্জাবী কালেকশন",
  "পাঞ্জাবির দাম",
  "পাঞ্জাবি পাইকারি",
];

const eidPunjabiKeywords = [
  "ঈদের পাঞ্জাবি",
  "পাঞ্জাবি",
  "কম দামে পাঞ্জাবি",
  "ঈদের পাঞ্জাবি কালেকশন",
  "পাঞ্জাবি পাইকারি মার্কেট",
  "কম পুঁজিতে পাঞ্জাবির ব্যবসা",
  "ঈদের নতুন পাঞ্জাবি",
  "নতুন ডিজাইন পাঞ্জাবি",
  "পাঞ্জাবি পাইকারি",
];

const giftPunjabiKeywords = [
  "পাঞ্জাবি গিফট পাঞ্জাবি",
  "পাঞ্জাবি গিফট",
  "পাঞ্জাবি গিফট করুন",
  "পাঞ্জাবি গিফট কম্বো বক্স",
  "পাঞ্জাবি কিনুন",
  "পাঞ্জাবি ডিজাইন",
  "পাঞ্জাবি পরার নিয়ম",
  "পাঞ্জাবি কেনার নিয়ম",
];

const shirtKeywords = [
  "শার্ট",
  "পাইকারি দামে শার্ট",
  "ছেলেদের শার্ট",
  "প্রিমিয়াম শার্ট",
  "শার্ট কিনুন",
  "কম দামে শার্ট",
  "টি শার্ট ব্যবসা",
  "ব্রান্ডের শার্ট",
  "পাইকারি টি শার্ট",
  "কালো ছেলেদের শার্ট",
  "শ্যামলা ছেলেদের শার্ট",
  "লটের শার্ট",
  "শার্ট কাটিং",
];

const pantKeywords = [
  "জিন্স প্যান্ট",
  "প্যান্ট",
  "ফরমাল প্যান্ট",
  "পাইকারি প্যান্ট",
  "প্যান্ট কেনার নিয়ম",
  "গ্যাবার্ডিন প্যান্ট",
  "পাইকারি জিন্স প্যান্ট",
  "ছেলেদের স্টাইলিশ প্যান্ট",
  "বয়েজ প্যান্ট",
  "জামা প্যান্ট",
];

const tShirtKeywords = [
  "টি শার্ট",
  "কম দামে টি শার্ট",
  "টি শার্ট ব্যবসা",
  "টি শার্ট পাইকারি বাজার",
  "পোলো টি শার্ট পাইকারি বাজার",
  "পাইকারি টি শার্ট",
  "টি শার্ট তৈরির কারখানা",
  "টি শার্ট ডিজাইন",
  "টি শার্ট পাইকারি",
  "পোলো শার্ট",
  "মাত্র ২৫ টাকায় টি শার্ট",
  "ভালো টি শার্ট",
  "নতুন টি শার্ট",
];

const burkaKeywords = [
  "বোরকা",
  "বোরকা ডিজাইন",
  "মাহুয়া বোরকা",
  "নতুন বোরকা",
  "সৌদি আরব বোরখা",
  "নতুন বোরকা ডিজাইন",
  "কটি বোরকা",
  "গাউন বোরকা",
  "মাহুয়া বোরকার ডিজাইন",
  "মহুয়া বোরকা",
  "আবায়া বোরকা",
  "ভাইরাল বোরকা",
];

const lowPriceBurkaKeywords = [
  "কম দামে বোরখা",
  "কম দামে বোরকা",
  "কম দামে বোকরা",
  "পাইকারি দামে বোরকা",
  "কম দামের বোরকা",
  "কম দামে বোরকা কালেকশন",
  "কম দামে দামি বোরকা",
  "প্রজাপতি বোরকা সবচেয়ে কম দামে",
  "অর্ধেক দামে বোরকা",
  "কমদামের প্রজাপতি বোরকা",
];

const honeyKeywords = [
  "মধু",
  "খাটি মধু",
  "খাঁটি মধু",
  "মধু চেনার উপায়",
  "দুধ ও মধু",
  "মধু খাওয়ার নিয়ম",
  "মধু ও লেবু",
  "সুগার মধু",
  "আসল মধু চেনার উপায়",
  "মধু খেলে কি উপকারিতা",
  "মধু খাওয়ার উপকারিতা",
  "বিশুদ্ধ মধু",
  "organic মধু",
  "মৌমাছির মধু",
  "মধু খাওয়ার উপকারিতা কি",
  "মধু খেলে কি হয়",
  "সুন্দরবন মধু",
  "খাটি মধু ডট কম",
  "মধু চিনার উপায়",
  "গাছের মধু নাকি",
  "খাঁটি মধু ডটকম",
  "দুধের সাথে মধু",
  "প্রাকৃতিক মধু",
  "কালোজিরা ও মধু",
  "মধু মাখলে কি হয়",
  "খাঁটি মধু কোথায় পাওয়া যায়",
  "মধু খেলে কি হয় ?",
  "সুন্দরবনের মধু",
];

const mustardFlowerHoneyKeywords = [
  "সরিষা ফুলের মধু",
  "ফুলের মধু",
  "সরিষা ফুলের মধু চেনার উপায়",
  "সরিষা ফুলের মধু চেনার উপায়",
  "#সরিষা ফুলের মধু",
  "সরিষা ফুলের মধু সংগ্রহ",
  "সরিষার ফুলের মধু",
  "সরিষা ফুলের খাঁটি মধু",
  "সরিষা ফুলের মধু চাষ পদ্ধতি",
];

const mixedFlowerHoneyKeywords = [
  "মিক্স ফুলের মধু মধু",
  "লিচু ফুলের মধু",
  "কালোজিরা ফুলের মধু",
  "খাঁটি মধু",
  "সুন্দরবনের প্রাকৃতিক চাক ভাঙ্গা মিক্স ফুলের মধু",
  "বরই ফুলের মধু",
  "গরান ফুলের মধু",
  "সরিষা ফুলের মধু",
  "খলিশা ফুলের মধু",
  "ধনিয়া ফুলের মধু",
  "বাইন কেওড়া ফুলের মধু",
  "খলিশা ফুলের চাকের মধু",
  "খলিশা ফুলের চাক ভাঙা মধু",
  "কোন ফুলের মধু সবচেয়ে বেশি উপকারী",
  "মধু বিক্রেতা আলামিন",
  "সুন্দরবনের মধু",
  "ত্বক ও চুলের সমস্যায় মধু",
  "মধু মাখলে কি হয়",
  "দুধের সাথে মধু",
  "মিকক্স ফুড দাম কত",
  "খাঁটি মধু পরীক্ষা",
  "মধু পরীক্ষা করার নিয়ম",
  "সেরা মধু",
  "পিউর মধু",
];

const aphrodisiacKeywords = [
  "হালূয়া",
  "সেক্স বাড়ানোর প্রাকৃতিক হালুয়া",
  "যৌন শক্তি বৃদ্ধির প্রাকৃতিক উপায়",
  "যৌনশক্তি বাড়ানোর প্রাকৃতিক উপায়",
  "দ্রুত বীর্যপাতের প্রাকৃতিক সমাধান",
  "মহিলাদের সেক্স বাড়ানোর উপায়",
  "যৌন ক্ষমতা বাড়ানোর পদ্ধতি",
  "সেক্স পাওয়ার বাড়ানোর ওষুধ",
  "সেক্স পাওয়ার বাড়ানোর উপায়",
  "যৌন ক্ষমতা বাড়ানোর পদ্ধতি ঔষধ",
  "যৌনশক্তি বাড়ানোর মন্ত্র",
  "যৌন ক্ষমতা বাড়ানোর পদ্ধতি",
  "যৌন শক্তি বাড়ানোর উপায়",
  "যৌনশক্তি বাড়ানোর ঘরোয়া রেমেডি",
  "যৌন ক্ষমতা বাড়ানোর আমল",
  "যৌন ক্ষমতা বাড়ানোর খাবার",
  "যৌন ক্ষমতা বাড়ানোর ঔষধ",
];

const herbalMedicineKeywords = [
  "হারবাল ওষুধ",
  "হারবাল",
  "হারবাল ঔষধ",
  "হারবাল ওষুধ",
  "হারবার ওষুধ",
  "হারবাল ওষুধ খেলে কি হয়",
  "হারবাল ওষুধ কি বেশি নিরাপ",
  "হারবাল ওষুধে বিষক্রিয়া",
  "বিষাক্ত রং দিয়ে হারবাল ওষুধ তৈরি",
  "কলিকাতা হারবাল",
  "হারবাল চিকিৎসা",
  "হারবাল ওষুধের নামে কি খাচ্ছেন?",
  "হারবাল শিল্প",
  "মডার্ন হারবাল",
  "মর্ডান হারবাল",
  "হারবাল ঔষধ শিল্প",
  "হারবাল ফেসিয়াল",
  "হারবাল ঔষদের নামে",
  "হারবাল থেকে মুক্তি",
  "দেশী হারবাল চিকিৎসা",
  "কোরিয়ান হারবাল ঔষধ",
  "ডায়াবেটিস এবং হারবাল",
  "হারবাল খেলে মৃত্যু হয়",
  "হারবাল ও আয়ুর্বেদিক চিকিৎসা",
];

const herbalRemedyKeywords = [
  "ভেষজ হারবাল রেমিডি",
  "হারবাল তেল",
  "হারবাল তেল রেসিপি",
  "ঘরে তৈরি হারবাল তেল",
  "হারবাল হেয়ার অয়েল রেসিপি",
  "চুলের যত্নে ম্যাজিক হারবাল তেল",
  "ভেষজ চা",
  "ভেষজ হালুয়া",
  "হারবাল#",
  "হারবাল জুস",
  "রেমিডি জুস ( হার্ট ব্লক জুস)",
  "হারবাল চিকিৎসা",
  "ন্যাচারাল হুম রেমিডি ফর হেয়ার#",
  "হারবাল হেয়ার অয়েল",
  "হারবাল শ্যাম্পু #",
  "ভেষজ",
  "চুলের যত্নে ঘরোয়া রেমিডি",
  "ম্যাজিক হারবাল তেল ঘরে তৈরি",
  "কিডনি রোগে ভেষজ",
  "নতুন চুল গজাতে ম্যাজিক হারবাল তেল",
  "ভেষজ তেল",
  "বীর্য্য গাঢ়া করার হারবাল মেডিসিন",
  "ভেষজ ঔষধ",
  "খুশকি দূর করবে হারবাল তেল",
];

const alkoshiKeywords = [
  "আলকুশি",
  "আলকুশি বীজের উপকারিতা",
  "আলকুশি বীজ",
  "আলকুশি বীজ শোধন পদ্ধতি",
  "আলকুশি বীজ খাওয়ার নিয়ম",
  "আলকুশি গাছ",
  "আলকুশি বীজ চূর্ণ",
  "আলকুশি কি",
];

const panchbhutaKeywords = [
  "পঞ্চভুত",
  "পঞ্চভুত খাওয়ার উপকারিতা",
  "পঞ্চভুত খাওয়ার সঠিক নিয়ম",
  "পঞ্চভূত",
  "পঞ্চভূত কি কি",
  "পঞ্চভুত কিভাবে তৈরি হয়",
  "পঞ্চভূত অর্থ",
  "পঞ্চভুত খেলে কি হয়",
  "পঞ্চভুত খাওয়ার নিয়ম",
  "পঞ্চভুত কি",
  "পঞ্চভুত কিভাবে খাবেন",
];

const ashwagandhaKeywords = [
  "অশ্বগন্ধা",
  "অশ্বগন্ধার উপকারিতা",
  "অশ্বগন্ধা পাউডার",
  "অশ্বগন্ধার উপকারিতা কি",
  "অশ্বগন্ধার উপকারিতা ও অপকারিতা",
];

const veeryamaniKeywords = [
  "বীর্যমনি",
  "বীর্যমনি ফল",
  "বীর্যমনি ফলের উপকারিতা",
  "বীর্যমনি ফল কি",
  "বীর্যমনী গাছ",
  "বীর্যমূল",
  "বীর্যমনি ফল খেলে কি হয়",
  "বীর্যমনি ফল উপকারিতা",
  "বীর্যমনি ফলের গুনাগুন",
];

const shimulKeywords = [
  "শিমুল",
  "শিমুল মুলের গুডা",
  "শিমুল মূলের উপকারিতা",
  "শিমুল গাছের মূলের উপকারিতা",
  "শিমুল মূল",
  "শিমুল মূলের উপকারিতা",
  "শিমুলের মূলের উপকারিতা",
  "শিমুল গাছ",
];

const banglishKeywords = [
  // Jeans Pants
  "jeans pant",
  "jeans pants",
  "kom dame jeans",
  "kom dame valo jeans pant",
  "jeans pant price in bangladesh",
  "jeans pant price in bd",
  "jeans",
  "export jeans pants",
  "denim jeans pant",
  "jeans pant price",
  "kom dame exporter pant",
  "jeans pant new collection",

  // Panjabi
  "panjabi",
  "panjabi price in bd",
  "panjabi price in bangladesh",
  "panjabi price",
  "panjabi price bd",
  "punjabi wholesale market",
  "indian panjabi price in bd",
  "best place to buy jamdani panjabi",
  "best place buy panjabi in bd",
  "panjabi price in bangladesh 2023",
  "best punjabi collection",
  "panjabi collection",
  "punjabi wholesale",
  "holuder panjabi",
  "new panjabi collection",
  "eid collection panjabi",

  // Shirt
  "shirt price in bd",
  "shirt",
  "t shirt",
  "formal shirt price in bd",
  "best quality shirt price in bangladesh",
  "t shirt bd",
  "formal u0026 casual shirt price in bd",
  "shirt bd",
  "bd shirt",
  "shirt stays in dhaka",
  "shirt in bd 2023",
  "polo shirt bd",
  "shirt price in bangladesh",
  "shirt stays in chittagong",
  "new design shirt",
  "shirt price",
  "shirt wholesale market in bangladesh",
  "check shirt price in bangladesh",
  "casual shirt price in bangladesh",
  "formal shirt price in bangladesh",

  // Tshirt
  "t shirt price in bangladesh",
  "hip hop t shirt price in bangladesh",
  "drop shoulder t shirt price in bangladesh",
  "cheap price new collection t shirt",
  "new t shirt collection in bangladesh",
  "shirt price",
  "t shirt price in bangladesh 2024",
  "t shirt price in bangladesh 2023",
  "hip hop t shirt",
  "new design t shirt for boys",
  "t shirt price bd",
  "new collections stylish mens t-shirt price in bangladesh 2024",
  "t shirt",
  "t shirt price in bd",

  // Borkha
  "borka price in bangladesh",
  "dubai borka price in bangladesh",
  "unique borka design price in bangladesh",
  "abaya borka price in bangladesh",
  "borka collection in bangladesh",
  "new borka collection in bangladesh",
  "party borka collection in bangladesh",
  "borka price in bangladesh 2022",
  "khimar borka price in bangladesh",
  "dubai borka collection in bangladesh",
  "dubai cherry borka price in bangladesh",
  "abaya borka design",
  "abaya borka design bangladesh",
  "stylish borka design",

  // Modhu
  "honey",
  "pure honey",
  "original honey",
  "sundarban honey bd",
  "natural honey",
  "organic honey",
  "imported honey brands in bd",
  "pure honey in bangladesh",
  "honey in bangladesh",
  "best honey in dhaka",
  "honey price in bangladesh",
  "honey collection in bd",

  // Halua
  "halwa recipe",
  "halwa",
  "suji ka halwa",
  "gajar ka halwa",
  "halua recipe",
  "sooji halwa",
  "carrot halwa",
  "gajar ka halwa recipe",
  "sooji ka halwa recipe",
  "sooji ka halwa",
  "bangladeshi halua recipe",
  "buter daler halua",
  "carrot halwa recipe",
  "daler halua",
  "buter halua",
  "gajor halua",
  "suji halwa",
  "gajar halwa recipe",
  "rava halwa",
  "halua recipe bangla",
];

export const allkeywords = [
  ...aphrodisiacKeywords,
  ...punjabiKeywords,
  ...burkaKeywords,
  ...eidPunjabiKeywords,
  ...giftPunjabiKeywords,
  ...herbalMedicineKeywords,
  ...herbalRemedyKeywords,
  ...honeyKeywords,
  ...lowPriceBurkaKeywords,
  ...mixedFlowerHoneyKeywords,
  ...mustardFlowerHoneyKeywords,
  ...pantKeywords,
  ...shirtKeywords,
  ...tShirtKeywords,
  ...alkoshiKeywords,
  ...panchbhutaKeywords,
  ...ashwagandhaKeywords,
  ...veeryamaniKeywords,
  ...shimulKeywords,
  ...banglishKeywords,
];

export const descriptionShop =
  "Welcome to Varimartbd.com, your premier destination for an unparalleled shopping experience! At Varimartbd.com, we pride ourselves on offering a vast array of high-quality products to meet all your needs and desires. Whether you're searching for the latest fashion trends, cutting-edge electronics, home essentials, or unique gifts, we've got you covered.\n\nWith a user-friendly interface and intuitive navigation, Varimartbd.com makes it easy for you to browse through our extensive collection of items. From clothing and accessories to gadgets and appliances, our diverse range ensures that there's something for everyone.\n\nAt Varimartbd.com, we are committed to providing our customers with top-notch service and exceptional value. Our team works tirelessly to source the best products from trusted brands and suppliers, ensuring that you receive nothing but the finest quality merchandise.\n\nShopping with us is not just about making a purchase—it's about embarking on a journey of discovery and delight. With new arrivals regularly added to our inventory, you'll always find something exciting and inspiring at Varimartbd.com.\n\nExperience the convenience of online shopping like never before with Varimartbd.com. Shop with confidence, knowing that your satisfaction is our top priority. Join us today and elevate your shopping experience to new heights!";
