import AuthProvider from "@/lib/AuthProvider";
import ReduxProvider from "@/lib/ReduxProvider";
import { cn } from "@/lib/utils";
import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import { Toaster } from "react-hot-toast";
import "./globals.css";

const poppins = Poppins({
  weight: ["400", "500", "600", "700", "800"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={cn(poppins.className, "w-full")}>
        <AuthProvider>
          <ReduxProvider>
            <div className="max-w-[1400px] mx-auto">
              {children}
              <Toaster position="top-center" reverseOrder={false} />
            </div>
          </ReduxProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
